### ISSUE TITLE
Double variables do "not seem to be constant within clusters"

### ISSUE THREAD

**Issue by jeandigitale** [simonheb/ritest#5] opened 2020-06-17 05:12 UTC
Hi Simon,

Hope you're well. I'm using ritest for three upcoming papers and hit a minor roadblock. I think that for some reason ritest does not want to permute double variables within clusters. I spent forever figuring out what distinguished the variables ritest gave me the error variable does "not seem to be constant within clusters" and realized they were all doubles rather than floats. 

I checked my variables were constant within clusters (they were) and simulated some variables below that were created to be constant within clusters. I get the error for the double variable below but not the float.

set seed 54321
gen double test_d = abs(rnormal())*3
bysort id: replace test_d = test_d[1]

gen float test_f = abs(rnormal())*3
bysort id: replace test_f = test_f[1]

ritest test_d test_d_c = _b[test_d], reps(3) cluster(id) noisily reject(e(converged)!=1) : ///
	melogit para_q test_d c.age_q##i.child male eir_ln ib3.siteid || hhid: || id:, or	
	
ritest test_f test_f_c = _b[test_f], reps(3) cluster(id) noisily reject(e(converged)!=1) : ///
	melogit para_q test_f c.age_q##i.child male eir_ln ib3.siteid || hhid: || id:, or	

I seem to have been able to get my code to run by changing the variables to be floats instead of doubles, but thought you might want to know.

Thanks,
Jean

**Comment by simonheb** [comment] 2020-06-24 18:41
Wow, I'm sure that was a nasty issue to debug for you. Thanks! I will sort this out in the next revision!!!

**Comment by jmseiden** [comment] 2021-01-17 21:49
I had a similar issue that took me a while to figure out--my clusters are strings which works fine for my normal command with clustered standard errors. However, when running ritest, I get the same error "treatment doesnt seem to be constant within clusters". Encoding my cluster variable so that it was a long numeric solved this. So it seems ritest requires the cluster variable to be numeric long. 

Happy to make a reproducible example if needed, but I think this issue is pretty clear.

**Comment by jmseiden** [comment] 2021-01-19 20:34
> I had a similar issue that took me a while to figure out--my clusters are strings which works fine for my normal command with clustered standard errors. However, when running ritest, I get the same error "treatment doesnt seem to be constant within clusters". Encoding my cluster variable so that it was a long numeric solved this. So it seems ritest requires the cluster variable to be numeric long.
> 
> Happy to make a reproducible example if needed, but I think this issue is pretty clear.

Please ignore this comment! I just realized this has been fixed; I was using an old release on my machine. Have just updated and problem solved. Thanks!

**Comment by simonheb** [comment] 2021-01-20 14:55
Oh ok, thanks. Sorry for the confusion. I might need to make sure that the latest code is not only available through github, but also on ssc

**Comment by simonheb** [comment] 2021-03-08 14:49
@jeandigitale, I will close this issue as I was not able to reproduce your issue with this code:

```
set seed 54321
clear
set obs 40 //clusters
gen double cluster=_n
gen double treatment=rnormal()
expand 2
gen y =treatment+rnormal()

ritest treatment _b[treatment] ,cluster(cluster): reg y treatment
```
If you (or someone else) comes across this issue again (and with the latest version of the code), please reopen the issue and provide an example code to reproduce the issue.

**Closed as completed by simonheb** 2021-03-08 14:49 UTC
